python gene_score_file.py --src_f es_wiki_align_00.sen.permute.filt.tok --tgt_f en_wiki_align_00.sen.permute.filt.tok --sco_f sif_score_00 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_01.sen.permute.filt.tok --tgt_f en_wiki_align_01.sen.permute.filt.tok --sco_f sif_score_01 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_02.sen.permute.filt.tok --tgt_f en_wiki_align_02.sen.permute.filt.tok --sco_f sif_score_02 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_03.sen.permute.filt.tok --tgt_f en_wiki_align_03.sen.permute.filt.tok --sco_f sif_score_03 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_04.sen.permute.filt.tok --tgt_f en_wiki_align_04.sen.permute.filt.tok --sco_f sif_score_04 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_05.sen.permute.filt.tok --tgt_f en_wiki_align_05.sen.permute.filt.tok --sco_f sif_score_05 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_06.sen.permute.filt.tok --tgt_f en_wiki_align_06.sen.permute.filt.tok --sco_f sif_score_06 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_07.sen.permute.filt.tok --tgt_f en_wiki_align_07.sen.permute.filt.tok --sco_f sif_score_07 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_08.sen.permute.filt.tok --tgt_f en_wiki_align_08.sen.permute.filt.tok --sco_f sif_score_08 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_09.sen.permute.filt.tok --tgt_f en_wiki_align_09.sen.permute.filt.tok --sco_f sif_score_09 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_10.sen.permute.filt.tok --tgt_f en_wiki_align_10.sen.permute.filt.tok --sco_f sif_score_10 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_11.sen.permute.filt.tok --tgt_f en_wiki_align_11.sen.permute.filt.tok --sco_f sif_score_11 --thre2 0.
python gene_score_file.py --src_f es_wiki_align_12.sen.permute.filt.tok --tgt_f en_wiki_align_12.sen.permute.filt.tok --sco_f sif_score_12 --thre2 0.
