../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_04.sen.permute.filt > en_wiki_align_04.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_01.sen.permute.filt > es_wiki_align_01.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_06.sen.permute.filt > en_wiki_align_06.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_09.sen.permute.filt > en_wiki_align_09.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_12.sen.permute.filt > es_wiki_align_12.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_03.sen.permute.filt > en_wiki_align_03.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_06.sen.permute.filt > es_wiki_align_06.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_02.sen.permute.filt > en_wiki_align_02.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_01.sen.permute.filt > en_wiki_align_01.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_02.sen.permute.filt > es_wiki_align_02.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_04.sen.permute.filt > es_wiki_align_04.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_07.sen.permute.filt > en_wiki_align_07.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_07.sen.permute.filt > es_wiki_align_07.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_08.sen.permute.filt > es_wiki_align_08.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_00.sen.permute.filt > en_wiki_align_00.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_05.sen.permute.filt > es_wiki_align_05.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_12.sen.permute.filt > en_wiki_align_12.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_10.sen.permute.filt > en_wiki_align_10.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_05.sen.permute.filt > en_wiki_align_05.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_09.sen.permute.filt > es_wiki_align_09.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_03.sen.permute.filt > es_wiki_align_03.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_10.sen.permute.filt > es_wiki_align_10.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l es -threads 24 < es_wiki_align_00.sen.permute.filt > es_wiki_align_00.sen.permute.filt.tok
../../mosesdecoder/scripts/tokenizer/tokenizer.perl -l en -threads 24 < en_wiki_align_08.sen.permute.filt > en_wiki_align_08.sen.permute.filt.tok
